spring:
  application:
    name: bookstore
  metrics:
    prometheus:
      enabled: true

  sleuth:
    sampler:
      percentage: 0.1 #(10% of the requests will be sampled)
  zipkin:
    baseUrl: http://localhost:9411/

server:
  port: 9080

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 50ms